name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - main

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # ------------------------------
#      - name: Make conda environment
#        uses: conda-incubator/setup-miniconda@v2
#        with:
#          python-version: 3.7    # Python version to build the html sphinx documentation
#          environment-file: devtools/conda-envs/docs_env.yaml    # Path to the documentation conda environment
#          auto-update-conda: false
#          auto-activate-base: false
#          show-channel-urls: true
      # ------------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Installing the Documentation requirements
        run: |
          pip3 install .[docs]
      # ------------------------------
      - name: Installing the library
        shell: bash -l {0}
        run: |
          python setup.py install
      - name: Installing pandoc
#        shell: bash -l {0}
        run: |
          apt-get install pandoc -y
      # ------------------------------
      - name: Copy readme and examples
        #            pwd
        #            ls -lh
        run: |
            cp ./examples ./documentation/examples -r
            cp ./README.md ./documentation/README.md

      - name: Running the Sphinx to gh-pages Action
        # https://github.com/marketplace/actions/sphinx-docs-to-github-pages
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0.0
        with:
          branch: main
          dir_docs: documentation
#          sphinxapiopts: '--separate -o . ../'
#          sphinxapiexclude: '../*setup* ../*.ipynb'
#          sphinxopts: ''