name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov pyarrow
          pip install -e .

      - name: Run tests with coverage
        run: pytest --cov=idf_analysis --cov-report=term-missing --cov-report=xml --cov-branch

      - name: Verify coverage report exists
        run: ls -l coverage.xml || { echo "coverage.xml not found!"; exit 1; }

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
